# Generated by Django 6.1.1 on 2026-09-06 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=100)),
                ('Report_type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=20)),
                ('Category', models.CharField(choices=[('document', 'Document'), ('electronic', 'Electronic'), ('accesories', 'Accesories'), ('books', 'Books'), ('other', 'Other')], max_length=20)),
                ('Description', models.TextField()),
                ('Location', models.CharField(max_length=250)),
                ('Date', models.DateField()),
                ('Contact_Info', models.CharField(max_length=250)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('Status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], max_length=20)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
